version: '3'
services:
  dynamic-dns-using-cloudflare:
    image: jedrzejme/dynamic-dns-using-cloudflare:latest
    container_name: dynamic-dns-using-cloudflare
    environment:
      - INTERVAL=
      - API_TOKEN=
      - ZONE_IDENTIFIER=
      - DOMAIN=
      - NAME=
      - TTL=
      - PROXIED=
      - COMMENT=Updated by Dynamic DNS using Cloudflare
    restart: unless-stopped